/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'interrupt' 
 * Target:  'interrupt' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "stm32f4xx.h"

/* Keil::Device:Startup@1.3.1 */
#define RTE_DEVICE_STARTUP_STM32F4xx    /* Device Startup for STM32F4 */
/* Keil::Device:StdPeriph Drivers:ADC@1.3.0 */
#define RTE_DEVICE_STDPERIPH_ADC
/* Keil::Device:StdPeriph Drivers:CAN@1.3.0 */
#define RTE_DEVICE_STDPERIPH_CAN
/* Keil::Device:StdPeriph Drivers:DMA@1.3.0 */
#define RTE_DEVICE_STDPERIPH_DMA
/* Keil::Device:StdPeriph Drivers:EXTI@1.3.0 */
#define RTE_DEVICE_STDPERIPH_EXTI
/* Keil::Device:StdPeriph Drivers:Flash@1.3.0 */
#define RTE_DEVICE_STDPERIPH_FLASH
/* Keil::Device:StdPeriph Drivers:Framework@1.3.1 */
#define RTE_DEVICE_STDPERIPH_FRAMEWORK
/* Keil::Device:StdPeriph Drivers:GPIO@1.3.0 */
#define RTE_DEVICE_STDPERIPH_GPIO
/* Keil::Device:StdPeriph Drivers:I2C@1.3.0 */
#define RTE_DEVICE_STDPERIPH_I2C
/* Keil::Device:StdPeriph Drivers:IWDG@1.3.0 */
#define RTE_DEVICE_STDPERIPH_IWDG
/* Keil::Device:StdPeriph Drivers:PWR@1.3.0 */
#define RTE_DEVICE_STDPERIPH_PWR
/* Keil::Device:StdPeriph Drivers:RCC@1.3.0 */
#define RTE_DEVICE_STDPERIPH_RCC
/* Keil::Device:StdPeriph Drivers:RTC@1.3.0 */
#define RTE_DEVICE_STDPERIPH_RTC
/* Keil::Device:StdPeriph Drivers:SPI@1.3.0 */
#define RTE_DEVICE_STDPERIPH_SPI
/* Keil::Device:StdPeriph Drivers:SYSCFG@1.3.0 */
#define RTE_DEVICE_STDPERIPH_SYSCFG
/* Keil::Device:StdPeriph Drivers:TIM@1.3.0 */
#define RTE_DEVICE_STDPERIPH_TIM
/* Keil::Device:StdPeriph Drivers:USART@1.3.0 */
#define RTE_DEVICE_STDPERIPH_USART


#endif /* RTE_COMPONENTS_H */
