#ifndef __TEMPERATURE_HUMIDITY_SENSOR_H__
#define __TEMPERATURE_HUMIDITY_SENSOR_H__

#include "stm32f4xx.h"
#define TEMPERATURE_HUMIDITY_SENSOR_GPIO   GPIOG
#define TEMPERATURE_HUMIDITY_SENSOR_GPIO_Pin    GPIO_Pin_9

#define TEMPERATURE_HUMIDITY_SENSOR_GPIO_OUT_HIGH  \
GPIO_SetBits(TEMPERATURE_HUMIDITY_SENSOR_GPIO, TEMPERATURE_HUMIDITY_SENSOR_GPIO_Pin)
#define TEMPERATURE_HUMIDITY_SENSOR_GPIO_OUT_LOW \
GPIO_ResetBits(TEMPERATURE_HUMIDITY_SENSOR_GPIO, TEMPERATURE_HUMIDITY_SENSOR_GPIO_Pin)
#define TEMPERATURE_HUMIDITY_SENSOR_GPIO_SWITCH(state) \
TEMPERATURE_HUMIDITY_SENSOR_GPIO_##state

#define TEMPERATURE_HUMIDITY_SENSOR_GPIO_IN_STATUS \
(TEMPERATURE_HUMIDITY_SENSOR_GPIO->IDR & TEMPERATURE_HUMIDITY_SENSOR_GPIO_Pin)


void temperature_humidity_sensor_init(void);
int32_t temperature_humidity_sensor_measure(void);
void temperature_humidity_set_IO_mode(GPIOMode_TypeDef mode);
int8_t temperature_humidity_sensor_check(void);



#endif



